# dataset
dataset:
  type: shapenet
  class: airplane # airplane, chair, car, multi ...
  num_gt_points: 2048

# model
model:
  id: test #TODO
  type: l-GAN
  noise_dim: 32
  generator:
    type: fc
    fc_hp:
      dims: [32, 128, 128]

  discriminator:
    type: fc
    fc_hp:
      dims: [128, 256, 512, 1]

  # configs of the pretrained AE
  AE_id: test #TODO

  encoder:
    type: pointnet
    GFV_dim: 128
    pointnet_hp:
      feat_dims_list: [3, 64, 64, 128, 128, 128]

  decoder:
    type: srtdecoder
    srtdecoder_hp:
      nlevels: 6
      feat_dims: [128, 64, 64, 64, 32, 32]
      num_output_points: 2048
    mrtdecoder_hp:
      nlevels: 6
      feat_dims: [128, 64, 64, 64, 32, 32]
      num_output_points: 2048
    topnet_hp:
      nlevels: 6
      node_feat_dim: 8
      num_output_points: 2048
    treegcn_hp:
      G_FEAT: [128, 128, 64, 64, 64, 32, 32, 3]
      DEGREE: [2, 2, 2, 4, 4, 4, 4]
      support: 10

train_setting:
  generator_optimizer:
    type: Adam
    beta1: 0.9
    beta2: 0.99
    init_lr: 0.0001

  discriminator_optimizer:
    type: Adam
    beta1: 0.5
    beta2: 0.99
    init_lr: 0.0001

  max_epoch: 2000
  batch_size: 32
  num_workers: 8
  epoch_per_eval: 10
  loss:
    type: w-gan-gp # vanilla-gan, ls-gan, w-gan-gp
    w-gan-gp_hp:
      lambdaGP: 10
  num_shapes_per_vis: 10


test_setting:
  batch_size: 64
  num_workers: 8
  num_evals: 10